### ISSUE TITLE
CI pipelines broken

### ISSUE THREAD

**Issue by oliworx** [cytopia/docker-phpcs#13]
The recent update of the image `cytopia/phpcs:3` broke our CI pipeline in GitLab:

_ERROR: Job failed (system failure): Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/ash": stat /bin/ash: no such file or directory: unknown (exec.go:57:0s)_

Seems like it not based on Alpine Linux anymore.

This used to be the job in GitLab:
```
codesniffer:
  stage: test
  cache: {}
  image:
    name: cytopia/phpcs:3
    entrypoint: [ "/bin/ash", "-c" ]
  before_script:
    - phpcs --version
  script:
    - phpcs
```

But now we have to find another way to check the code style.
